<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CloudManager</RootNamespace>
    <CodeAnalysisRuleSet>..\..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.APIGateway" Version="4.0.7.1" />
    <PackageReference Include="AWSSDK.CertificateManager" Version="4.0.4.1" />
    <PackageReference Include="AWSSDK.CloudFront" Version="4.0.16.2" />
    <PackageReference Include="AWSSDK.CloudWatch" Version="4.0.10.5" />
    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.7" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.8" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.7.3" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.18.5" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.90" />
    <PackageReference Include="AWSSDK.ECR" Version="4.0.8" />
    <PackageReference Include="AWSSDK.ECS" Version="4.0.21.1" />
    <PackageReference Include="AWSSDK.ElasticLoadBalancingV2" Version="4.0.6.27" />
    <PackageReference Include="AWSSDK.EventBridge" Version="4.0.5.33" />
    <PackageReference Include="AWSSDK.Lambda" Version="4.0.15.6" />
    <PackageReference Include="AWSSDK.Pricing" Version="4.0.5.1" />
    <PackageReference Include="AWSSDK.RDS" Version="4.0.20.7" />
    <PackageReference Include="AWSSDK.Route53" Version="4.0.8.27" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23.4" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.4.14" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.2.34" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.7.18" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.32" />
    <PackageReference Include="BunnyTail.ServiceRegistration" Version="1.18.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Usa.Smart.Core" Version="2.19.0" />
    <PackageReference Include="Usa.Smart.Data.Accessor" Version="3.0.0-beta7" />
    <PackageReference Include="Usa.Smart.Data.Accessor.Extensions.DependencyInjection" Version="3.0.0-beta7" />
    <PackageReference Include="Usa.Smart.Mapper" Version="1.0.0-beta9" />
  </ItemGroup>

</Project>
